### PR TITLE
Corrected grammar

### PR DESCRIPTION
**Pull request by AndrewBudziszek**

### CODE REVIEW

**Comment by joeythomaschaske** [comment]
Grammar is correct and intentional.

**Comment by AndrewBudziszek** [comment]
Grammar is potentially offending to some nationalities.

**Comment by joeythomaschaske** [comment]
@SonnyBrooks github is not a safespace. Git your mind out of the gutter, this is the noise my cat makes.

**Comment by ghost** [comment]
@joeythomaschaske  Github should be an inclusive space that considers diversity. My mind was not in the gutter, I just know that my cat would be offended by this particular stereotype of cat sounds.

**Pull request closed without merging**
